language: php
php:
  - '7.1'

before_script:
  - composer self-update
  - composer install --no-interaction
  - mkdir -p build/logs

install:
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - ./vendor/bin/phpcs

after_success:
  - php vendor/bin/coveralls -v